vich_uploader:
    db_driver: orm
    
    mappings:
        event_banners:
            uri_prefix: /uploads/events
            upload_destination: '%kernel.project_dir%/public/uploads/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        event_files:
            uri_prefix: /uploads/event_files
            upload_destination: '%kernel.project_dir%/public/uploads/event_files'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        presenter_photos:
            uri_prefix: /uploads/presenters
            upload_destination: '%kernel.project_dir%/public/uploads/presenters'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        featured_event_banners:
            uri_prefix: /uploads/featured_events
            upload_destination: '%kernel.project_dir%/public/uploads/featured_events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
