# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Application Logger Service with specific channels
    App\Service\ApplicationLogger:
        arguments:
            $logger: '@monolog.logger'
            $securityLogger: '@monolog.logger.security'
            $auditLogger: '@monolog.logger.audit'
            $eventMgmtLogger: '@monolog.logger.event_mgmt'
            $userMgmtLogger: '@monolog.logger.user_mgmt'
            $appErrorLogger: '@monolog.logger.app_error'
    
    # Log Cleanup Command
    App\Command\LogCleanupCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
    
    # Admin Log Controller
    App\Controller\Admin\AdminLogController:
        arguments:
            $projectDir: '%kernel.project_dir%'
